language: node_js

branches:
  only:
  - master

os:
  - linux

node_js:
  - node

jobs:
  include: 
  - stage: Build
    script: npm ci
  - stage: Lint
    script: npm run lint
  - stage: Tests
    script: npm run test

notifications:
  - email: false
