sudo: false

language: node_js

node_js:
  - node

addons:
  chrome: stable

install:
  - npm ci

script:
  - google-chrome-stable --disable-gpu --remote-debugging-port=9222 http://localhost:8080
  - npm test