language: node_js

branches:
  only:
    - master

os:
  - linux

node_js:
  - node

jobs:
  include:
    - stage: Lint
      script: npm run lint
    - stage: Tests
      script: npm run build:dev && npm run test
    - stage: Publish
      script: npx semantic-release

notifications:
  - email: false
