sudo: false

language: node_js

node_js:
  - node

addons:
  chrome: stable

install:
  - npm ci

script:
  - npm test

after_script: NODE_ENV=test nyc cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage