sudo: false

language: node_js

node_js:
  - node

addons:
  chrome: stable

install:
  - npm ci

before_install:
  - # start your web application and listen on `localhost`
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost:8080

script:
  - npm test
